version: "3.9"
services:
  db:
    image: postgres
    container_name: candidates-sending-db
    volumes:
      - ce-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake db:create && rake db:migrate && rake db:seed || rake db:migrate rake db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/candidates_sending
    ports:
      - "80:3000"
    depends_on:
      - db
volumes:
  ce-postgres:
