require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/candidates", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Candidate. As you add validations to Candidate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Candidate.create! valid_attributes
      get candidates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      candidate = Candidate.create! valid_attributes
      get candidate_url(candidate)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_candidate_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      candidate = Candidate.create! valid_attributes
      get edit_candidate_url(candidate)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Candidate" do
        expect {
          post candidates_url, params: { candidate: valid_attributes }
        }.to change(Candidate, :count).by(1)
      end

      it "redirects to the created candidate" do
        post candidates_url, params: { candidate: valid_attributes }
        expect(response).to redirect_to(candidate_url(Candidate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Candidate" do
        expect {
          post candidates_url, params: { candidate: invalid_attributes }
        }.to change(Candidate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post candidates_url, params: { candidate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested candidate" do
        candidate = Candidate.create! valid_attributes
        patch candidate_url(candidate), params: { candidate: new_attributes }
        candidate.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the candidate" do
        candidate = Candidate.create! valid_attributes
        patch candidate_url(candidate), params: { candidate: new_attributes }
        candidate.reload
        expect(response).to redirect_to(candidate_url(candidate))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        candidate = Candidate.create! valid_attributes
        patch candidate_url(candidate), params: { candidate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested candidate" do
      candidate = Candidate.create! valid_attributes
      expect {
        delete candidate_url(candidate)
      }.to change(Candidate, :count).by(-1)
    end

    it "redirects to the candidates list" do
      candidate = Candidate.create! valid_attributes
      delete candidate_url(candidate)
      expect(response).to redirect_to(candidates_url)
    end
  end
end
