require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/jobs_candidates_pipelines", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # JobsCandidatesPipeline. As you add validations to JobsCandidatesPipeline, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JobsCandidatesPipeline.create! valid_attributes
      get jobs_candidates_pipelines_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      jobs_candidates_pipeline = JobsCandidatesPipeline.create! valid_attributes
      get jobs_candidates_pipeline_url(jobs_candidates_pipeline)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_jobs_candidates_pipeline_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      jobs_candidates_pipeline = JobsCandidatesPipeline.create! valid_attributes
      get edit_jobs_candidates_pipeline_url(jobs_candidates_pipeline)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JobsCandidatesPipeline" do
        expect {
          post jobs_candidates_pipelines_url, params: { jobs_candidates_pipeline: valid_attributes }
        }.to change(JobsCandidatesPipeline, :count).by(1)
      end

      it "redirects to the created jobs_candidates_pipeline" do
        post jobs_candidates_pipelines_url, params: { jobs_candidates_pipeline: valid_attributes }
        expect(response).to redirect_to(jobs_candidates_pipeline_url(JobsCandidatesPipeline.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JobsCandidatesPipeline" do
        expect {
          post jobs_candidates_pipelines_url, params: { jobs_candidates_pipeline: invalid_attributes }
        }.to change(JobsCandidatesPipeline, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post jobs_candidates_pipelines_url, params: { jobs_candidates_pipeline: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jobs_candidates_pipeline" do
        jobs_candidates_pipeline = JobsCandidatesPipeline.create! valid_attributes
        patch jobs_candidates_pipeline_url(jobs_candidates_pipeline), params: { jobs_candidates_pipeline: new_attributes }
        jobs_candidates_pipeline.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the jobs_candidates_pipeline" do
        jobs_candidates_pipeline = JobsCandidatesPipeline.create! valid_attributes
        patch jobs_candidates_pipeline_url(jobs_candidates_pipeline), params: { jobs_candidates_pipeline: new_attributes }
        jobs_candidates_pipeline.reload
        expect(response).to redirect_to(jobs_candidates_pipeline_url(jobs_candidates_pipeline))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        jobs_candidates_pipeline = JobsCandidatesPipeline.create! valid_attributes
        patch jobs_candidates_pipeline_url(jobs_candidates_pipeline), params: { jobs_candidates_pipeline: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested jobs_candidates_pipeline" do
      jobs_candidates_pipeline = JobsCandidatesPipeline.create! valid_attributes
      expect {
        delete jobs_candidates_pipeline_url(jobs_candidates_pipeline)
      }.to change(JobsCandidatesPipeline, :count).by(-1)
    end

    it "redirects to the jobs_candidates_pipelines list" do
      jobs_candidates_pipeline = JobsCandidatesPipeline.create! valid_attributes
      delete jobs_candidates_pipeline_url(jobs_candidates_pipeline)
      expect(response).to redirect_to(jobs_candidates_pipelines_url)
    end
  end
end
