require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/point_of_contacts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PointOfContact. As you add validations to PointOfContact, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PointOfContact.create! valid_attributes
      get point_of_contacts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      point_of_contact = PointOfContact.create! valid_attributes
      get point_of_contact_url(point_of_contact)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_point_of_contact_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      point_of_contact = PointOfContact.create! valid_attributes
      get edit_point_of_contact_url(point_of_contact)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PointOfContact" do
        expect {
          post point_of_contacts_url, params: { point_of_contact: valid_attributes }
        }.to change(PointOfContact, :count).by(1)
      end

      it "redirects to the created point_of_contact" do
        post point_of_contacts_url, params: { point_of_contact: valid_attributes }
        expect(response).to redirect_to(point_of_contact_url(PointOfContact.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PointOfContact" do
        expect {
          post point_of_contacts_url, params: { point_of_contact: invalid_attributes }
        }.to change(PointOfContact, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post point_of_contacts_url, params: { point_of_contact: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested point_of_contact" do
        point_of_contact = PointOfContact.create! valid_attributes
        patch point_of_contact_url(point_of_contact), params: { point_of_contact: new_attributes }
        point_of_contact.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the point_of_contact" do
        point_of_contact = PointOfContact.create! valid_attributes
        patch point_of_contact_url(point_of_contact), params: { point_of_contact: new_attributes }
        point_of_contact.reload
        expect(response).to redirect_to(point_of_contact_url(point_of_contact))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        point_of_contact = PointOfContact.create! valid_attributes
        patch point_of_contact_url(point_of_contact), params: { point_of_contact: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested point_of_contact" do
      point_of_contact = PointOfContact.create! valid_attributes
      expect {
        delete point_of_contact_url(point_of_contact)
      }.to change(PointOfContact, :count).by(-1)
    end

    it "redirects to the point_of_contacts list" do
      point_of_contact = PointOfContact.create! valid_attributes
      delete point_of_contact_url(point_of_contact)
      expect(response).to redirect_to(point_of_contacts_url)
    end
  end
end
