require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/recruiters", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Recruiter. As you add validations to Recruiter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Recruiter.create! valid_attributes
      get recruiters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      recruiter = Recruiter.create! valid_attributes
      get recruiter_url(recruiter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_recruiter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      recruiter = Recruiter.create! valid_attributes
      get edit_recruiter_url(recruiter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Recruiter" do
        expect {
          post recruiters_url, params: { recruiter: valid_attributes }
        }.to change(Recruiter, :count).by(1)
      end

      it "redirects to the created recruiter" do
        post recruiters_url, params: { recruiter: valid_attributes }
        expect(response).to redirect_to(recruiter_url(Recruiter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Recruiter" do
        expect {
          post recruiters_url, params: { recruiter: invalid_attributes }
        }.to change(Recruiter, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post recruiters_url, params: { recruiter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested recruiter" do
        recruiter = Recruiter.create! valid_attributes
        patch recruiter_url(recruiter), params: { recruiter: new_attributes }
        recruiter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the recruiter" do
        recruiter = Recruiter.create! valid_attributes
        patch recruiter_url(recruiter), params: { recruiter: new_attributes }
        recruiter.reload
        expect(response).to redirect_to(recruiter_url(recruiter))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        recruiter = Recruiter.create! valid_attributes
        patch recruiter_url(recruiter), params: { recruiter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested recruiter" do
      recruiter = Recruiter.create! valid_attributes
      expect {
        delete recruiter_url(recruiter)
      }.to change(Recruiter, :count).by(-1)
    end

    it "redirects to the recruiters list" do
      recruiter = Recruiter.create! valid_attributes
      delete recruiter_url(recruiter)
      expect(response).to redirect_to(recruiters_url)
    end
  end
end
